apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w1y2nd8kn-go 
  janus-idp.io/tekton: w1y2nd8kn-go
  backstage.io/kubernetes-id: w1y2nd8kn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w1y2nd8kn-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  