apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: w1y2nd8kn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: w1y2nd8kn-go 
  name: w1y2nd8kn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: w1y2nd8kn-go 
